# Generated by Django 4.1 on 2022-09-16 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="files",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["xml", ""],
                                message="You must only upload .xml or .json file.",
                            )
                        ],
                    ),
                ),
            ],
        ),
    ]
