# Generated by Django 4.1 on 2022-09-18 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hw1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="jsonFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="json",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["json"],
                                message="You must only upload .xml or .json file.",
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="XMLFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="xml",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["xml"],
                                message="You must only upload .xml or .json file.",
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="File",),
    ]
