# Generated by Django 4.1 on 2022-09-18 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hw1", "0002_jsonfile_xmlfile_delete_file"),
    ]

    operations = [
        migrations.DeleteModel(name="jsonFile",),
        migrations.DeleteModel(name="XMLFile",),
    ]
